name: Daglig scraper

on:
  schedule:
    - cron: '0 6 * * *'  # kører hver dag kl. 06:00 UTC = 08:00 dansk tid
  workflow_dispatch:      # tillader manuel start

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Hent kode fra GitHub
        uses: actions/checkout@v2

      - name: Installer Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Kør script
        run: python scraper.py
